export interface Formation {
  id?: number;            // Optional field, since it might be auto-generated by the backend
  dateFormation: Date;    // Date object representing the date of the formation
  description: string;    // Description of the formation
  nomFormation: string;   // Name of the formation
  nombrePlace: number;
  prix: number;         // Price of the formation
}
